#!/bin/sh

tar -c -f - \
    --exclude '*~' \
    --exclude '*.orig' \
    --exclude '.gitignore' \
    FlyingBrick.blend \
    Project/PackageSources |
    (cd /Volumes/stinky/Users/tml/OneDrive/flying-brick && tar xvf -)
